### PR TITLE
[BUGFIX] Fixed bug showing 1 problem on UserProfile

### LINKED ISSUE #22: Only 1 submission/contest on User Profile
Fixed by #23

### PR DESCRIPTION
**Pull request by eh2arch**
Fixes #22  @Solved should be instantiated by default with an []

### CODE REVIEW

File: app/controllers/user_controller.rb [hunk 1]
```diff
@@ -54,19 +54,15 @@ def profile
     problems = submissions.where(status_code: 'AC').distinct(:problem)
     @total_currect = problems.count
     solved_problem = []
-    @solved = {}
+    @solved = Hash.new []
```
Comment (kumarneetesh24) [inline app/controllers/user_controller.rb]: Array should be instantiated inside hash initialization.
